language: scala
jdk:
  - oraclejdk8
sbt_args: -Xmx2048M
script:
  - sbt coverage test
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
  - sbt coverageReport
  - bash <(curl -s https://codecov.io/bash)

sudo: false

# Cache settings
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers

# whitelist
branches:
  only:
    - master